import { HairstyleOption } from './types';

export const HAIRSTYLES: HairstyleOption[] = [
  // Short / Military / Clean
  {
    id: 'buzz_cut',
    name: 'Buzz Cut',
    description: 'Ultra-short, uniform length all around using clippers. Rugged, masculine, and low maintenance.',
    gender: 'male',
    previewColor: 'bg-stone-600',
  },
  {
    id: 'induction_cut',
    name: 'Induction Cut',
    description: 'The shortest possible haircut without shaving the head completely. Military standard.',
    gender: 'male',
    previewColor: 'bg-stone-500',
  },
  {
    id: 'crew_cut',
    name: 'Crew Cut',
    description: 'Short on the sides, slightly longer on top. A timeless professional look.',
    gender: 'male',
    previewColor: 'bg-emerald-600',
  },
  {
    id: 'ivy_league',
    name: 'Ivy League',
    description: 'Similar to a crew cut but long enough on top to part on the side. Smart and preppy.',
    gender: 'male',
    previewColor: 'bg-emerald-700',
  },
  {
    id: 'high_and_tight',
    name: 'High and Tight',
    description: 'Very short sides and back with a slightly longer patch on the top. Classic military style.',
    gender: 'male',
    previewColor: 'bg-stone-700',
  },
  {
    id: 'flat_top',
    name: 'Flat Top',
    description: 'Hair on top is cut to stand upright and form a flat deck. Distinctive and bold.',
    gender: 'male',
    previewColor: 'bg-amber-700',
  },
  {
    id: 'caesar_cut',
    name: 'Caesar Cut',
    description: 'Short hair with a straight horizontal fringe styled forward. Classic and effective.',
    gender: 'male',
    previewColor: 'bg-teal-600',
  },
  {
    id: 'french_crop',
    name: 'French Crop',
    description: 'Short back and sides with a textured top and cropped fringe. Modern and low-maintenance.',
    gender: 'male',
    previewColor: 'bg-teal-500',
  },

  // Fades
  {
    id: 'low_fade',
    name: 'Low Fade',
    description: 'Tapering begins low just above the ears and neckline for a subtle clean look.',
    gender: 'male',
    previewColor: 'bg-sky-600',
  },
  {
    id: 'mid_fade',
    name: 'Mid Fade',
    description: 'Fade starts in the middle of the head, between the ears and temples.',
    gender: 'male',
    previewColor: 'bg-sky-500',
  },
  {
    id: 'high_fade',
    name: 'High Fade',
    description: 'Fade starts high up near the top of the head for high contrast.',
    gender: 'male',
    previewColor: 'bg-sky-400',
  },
  {
    id: 'skin_fade',
    name: 'Skin Fade',
    description: 'Sides are shaved down to the skin, blending into longer hair on top.',
    gender: 'male',
    previewColor: 'bg-slate-600',
  },
  {
    id: 'burst_fade',
    name: 'Burst Fade',
    description: 'Fade curves around the ear while leaving length at the back. Athletic and edgy.',
    gender: 'male',
    previewColor: 'bg-violet-600',
  },
  {
    id: 'drop_fade',
    name: 'Drop Fade',
    description: 'The fade line drops lower behind the ear to follow the head shape.',
    gender: 'male',
    previewColor: 'bg-indigo-500',
  },
  {
    id: 'taper_fade',
    name: 'Taper Fade',
    description: 'Clean fade at the sideburns and neckline while keeping length behind the ears.',
    gender: 'male',
    previewColor: 'bg-cyan-500',
  },

  // Classic / Gentleman
  {
    id: 'pompadour',
    name: 'Pompadour',
    description: 'High volume on top, swept upwards and back. A rock and roll classic.',
    gender: 'male',
    previewColor: 'bg-blue-600',
  },
  {
    id: 'quiff',
    name: 'Quiff',
    description: 'Voluminous forelock swept up and back. Less structured than a pompadour, very versatile.',
    gender: 'male',
    previewColor: 'bg-blue-500',
  },
  {
    id: 'slicked_back',
    name: 'Slicked Back',
    description: 'Hair combed straight back using pomade. Classic business or bad-boy look.',
    gender: 'male',
    previewColor: 'bg-slate-800',
  },
  {
    id: 'side_part',
    name: 'Classic Side Part',
    description: 'Clean, defined part on one side. The quintessential gentleman\'s cut.',
    gender: 'male',
    previewColor: 'bg-indigo-700',
  },
  {
    id: 'hard_part',
    name: 'Hard Part',
    description: 'A shaved line creates a distinct, sharp parting for a modern look.',
    gender: 'male',
    previewColor: 'bg-indigo-800',
  },
  {
    id: 'comb_over',
    name: 'Comb Over',
    description: 'Longer hair on top combed to one side, often paired with a fresh fade.',
    gender: 'male',
    previewColor: 'bg-blue-700',
  },

  // Modern / Trendy
  {
    id: 'undercut',
    name: 'Undercut',
    description: 'Short sides and back with significantly longer hair on top, no fading.',
    gender: 'male',
    previewColor: 'bg-cyan-600',
  },
  {
    id: 'disconnected_undercut',
    name: 'Disconnected Undercut',
    description: 'Sharp contrast between the shaved sides and long top with no blending.',
    gender: 'male',
    previewColor: 'bg-cyan-700',
  },
  {
    id: 'textured_fringe',
    name: 'Textured Fringe',
    description: 'Messy, textured hair hanging over the forehead. Youthful and stylish.',
    gender: 'male',
    previewColor: 'bg-lime-600',
  },
  {
    id: 'curly_fringe',
    name: 'Curly Fringe',
    description: 'Natural or permed curls falling over the forehead with short sides.',
    gender: 'male',
    previewColor: 'bg-lime-700',
  },
  {
    id: 'spiky',
    name: 'Spiky Hair',
    description: 'Short to medium hair styled upwards into texture spikes.',
    gender: 'male',
    previewColor: 'bg-yellow-600',
  },
  {
    id: 'two_block',
    name: 'Two Block',
    description: 'Shaved sides and lower back, with long flowy hair on the crown. Popular K-pop style.',
    gender: 'male',
    previewColor: 'bg-pink-600',
  },
  {
    id: 'curtains',
    name: 'Curtains',
    description: 'Long fringe divided in the middle or slightly to the side. 90s grunge revival.',
    gender: 'male',
    previewColor: 'bg-violet-500',
  },
  {
    id: 'wolf_cut',
    name: 'Wolf Cut',
    description: 'Wild, shaggy layers with a mullet-like shape. Rugged and highly textured.',
    gender: 'male',
    previewColor: 'bg-red-500',
  },
  {
    id: 'mullet',
    name: 'Modern Mullet',
    description: 'Business in the front, party in the back. Short front/sides, long back with texture.',
    gender: 'male',
    previewColor: 'bg-orange-600',
  },
  {
    id: 'mohawk',
    name: 'Mohawk',
    description: 'Shaved sides with a dramatic strip of upright hair in the center.',
    gender: 'male',
    previewColor: 'bg-red-700',
  },
  {
    id: 'faux_hawk',
    name: 'Faux Hawk',
    description: 'Resembles a mohawk but with tapered sides instead of shaved skin.',
    gender: 'male',
    previewColor: 'bg-red-400',
  },

  // Long / Tie-up
  {
    id: 'man_bun',
    name: 'Man Bun',
    description: 'Long hair tied back into a bun on the crown or back of the head.',
    gender: 'male',
    previewColor: 'bg-neutral-600',
  },
  {
    id: 'top_knot',
    name: 'Top Knot',
    description: 'A bun tied high on top, usually paired with shaved or faded sides.',
    gender: 'male',
    previewColor: 'bg-neutral-700',
  },
  {
    id: 'bro_flow',
    name: 'Bro Flow',
    description: 'Medium to long hair swept back naturally. Relaxed, wavy, and charming.',
    gender: 'male',
    previewColor: 'bg-teal-400',
  },
  {
    id: 'surfer_hair',
    name: 'Surfer / Shaggy',
    description: 'Long, tousled, sun-bleached look. Low maintenance and chill.',
    gender: 'male',
    previewColor: 'bg-orange-400',
  },

  // Textured / Afro
  {
    id: 'afro',
    name: 'Afro',
    description: 'Natural growth, rounded and voluminous.',
    gender: 'male',
    previewColor: 'bg-amber-700',
  },
  {
    id: 'cornrows',
    name: 'Cornrows',
    description: 'Tight braids close to the scalp in straight lines or geometric patterns.',
    gender: 'male',
    previewColor: 'bg-stone-800',
  },
  {
    id: 'dreadlocks',
    name: 'Dreadlocks',
    description: 'Rope-like strands of hair formed by matting or braiding.',
    gender: 'male',
    previewColor: 'bg-stone-600',
  },
  {
    id: 'waves_360',
    name: '360 Waves',
    description: 'Short hair brushed to create a ripple-like wave pattern.',
    gender: 'male',
    previewColor: 'bg-blue-900',
  },
  
  // No Hair
  {
    id: 'bald',
    name: 'Bald / Shaved',
    description: 'Completely shaved head. Clean, bold, and masculine.',
    gender: 'male',
    previewColor: 'bg-slate-400',
  },
];